/* ============================================================
   NOTEBOOK ("Carnet"): the searchable help library.
   Each entry: id, cat, title, sum (one line), body (HTML), syntax,
   example (HTML), tip (HTML), kw (extra search words, both languages),
   lessons (ids of lessons that use it).
   NOTES_FOR maps a lesson (or "lessonId:questionIndex") to the entries
   offered by its "Besoin d'aide ?" button.
   ============================================================ */
(() => {
  window.NOTEBOOK_CATS = [
    { id: 'fn', title: T('Fonctions', 'Functions') },
    { id: 'basics', title: T('Notions de base', 'Basics') },
    { id: 'keys', title: T('Raccourcis', 'Shortcuts') },
    { id: 'err', title: T('Erreurs', 'Errors') },
    { id: 'fin', title: T('Finance', 'Finance') },
    { id: 'design', title: T('Design', 'Design') },
  ];

  const E = (id, cat, title, sum, body, extra = {}) => Object.assign({ id, cat, title, sum, body }, extra);

  window.NOTEBOOK = [
    /* ------------------------------------------------------------ functions */
    E('sum', 'fn', T('SOMME', 'SUM'), T('Additionne une plage de cellules.', 'Adds up a range of cells.'),
      T(`<p>Additionne tous les nombres d'une plage. Les cellules vides et le texte sont ignorés.</p>`, `<p>Adds all the numbers in a range. Empty cells and text are ignored.</p>`),
      { syntax: T('=SOMME(B2:B5)', '=SUM(B2:B5)'), example: T('<code>=SOMME(B2:B5)</code> additionne B2, B3, B4 et B5.', '<code>=SUM(B2:B5)</code> adds B2, B3, B4 and B5.'),
        tip: T('Alt + = écrit la SOMME pour toi.', 'Alt + = writes the SUM for you.'), kw: 'additionner total somme sum add total', lessons: ['f2'] }),
    E('average', 'fn', T('MOYENNE', 'AVERAGE'), T('Calcule la moyenne.', 'Calculates the average.'),
      T(`<p>Additionne les valeurs puis divise par leur nombre. Les cellules <strong>vides</strong> sont ignorées, mais un <code>0</code> est compté.</p>`, `<p>Adds the values then divides by how many there are. <strong>Empty</strong> cells are ignored, but a <code>0</code> is counted.</p>`),
      { syntax: T('=MOYENNE(B2:B5)', '=AVERAGE(B2:B5)'), kw: 'moyenne average mean', lessons: ['f3'] }),
    E('minmax', 'fn', T('MIN et MAX', 'MIN and MAX'), T('La plus petite et la plus grande valeur.', 'The smallest and the largest value.'),
      T(`<p><code>MAX</code> donne la plus grande valeur d'une plage, <code>MIN</code> la plus petite. On peut les combiner : <code>MAX − MIN</code> donne l'écart.</p>`, `<p><code>MAX</code> gives the largest value of a range, <code>MIN</code> the smallest. You can combine them: <code>MAX − MIN</code> gives the gap.</p>`),
      { syntax: T('=MAX(B2:B5)-MIN(B2:B5)', '=MAX(B2:B5)-MIN(B2:B5)'), kw: 'minimum maximum ecart plus grand plus petit smallest largest', lessons: ['f4'] }),
    E('counta', 'fn', T('NBVAL et NB', 'COUNTA and COUNT'), T('Compte des cellules.', 'Counts cells.'),
      T(`<p><code>NBVAL</code> compte les cellules <strong>non vides</strong> (texte ou nombres). <code>NB</code> ne compte que les <strong>nombres</strong>.</p>`, `<p><code>COUNTA</code> counts <strong>non-empty</strong> cells (text or numbers). <code>COUNT</code> counts only <strong>numbers</strong>.</p>`),
      { syntax: T('=NBVAL(A8:A17)', '=COUNTA(A8:A17)'), kw: 'compter nombre de lignes count nbval nb', lessons: ['p2'] }),
    E('if', 'fn', T('SI', 'IF'), T('Choisit entre deux résultats selon une condition.', 'Chooses between two results depending on a condition.'),
      T(`<p>Teste une condition : si elle est vraie, Excel renvoie le premier résultat, sinon le second. Opérateurs : <code>&gt;</code> <code>&lt;</code> <code>&gt;=</code> <code>&lt;=</code> <code>=</code> <code>&lt;&gt;</code>.</p>`, `<p>Tests a condition: if true, Excel returns the first result, otherwise the second. Operators: <code>&gt;</code> <code>&lt;</code> <code>&gt;=</code> <code>&lt;=</code> <code>=</code> <code>&lt;&gt;</code>.</p>`),
      { syntax: T('=SI(B2>=1000;100;0)', '=IF(B2>=1000,100,0)'), example: T('Bonus de 100 $ si les ventes sont d\'au moins 1000 $, sinon 0.', 'A $100 bonus if sales are at least $1000, otherwise 0.'),
        tip: T('Le texte va entre guillemets : <code>"Oui"</code>.', 'Text goes between quotes: <code>"Yes"</code>.'), kw: 'condition si if test comparer', lessons: ['f5'] }),
    E('nested-if', 'fn', T('SI imbriqués', 'Nested IFs'), T('Plusieurs cas : un SI dans un SI.', 'Several cases: an IF inside an IF.'),
      T(`<p>Pour plus de deux résultats, mets un <code>SI</code> à la place du « sinon ». Excel s'arrête au premier cas vrai, donc teste du <strong>plus exigeant au moins exigeant</strong>.</p>`, `<p>For more than two results, put an <code>IF</code> in place of the "else". Excel stops at the first true case, so test from <strong>most demanding to least demanding</strong>.</p>`),
      { syntax: T('=SI(B2>=1000;"Or";SI(B2>=500;"Argent";"Bronze"))', '=IF(B2>=1000,"Gold",IF(B2>=500,"Silver","Bronze"))'), kw: 'plusieurs conditions paliers if imbriques', lessons: ['f9'] }),
    E('and-or', 'fn', T('ET et OU', 'AND and OR'), T('Combine plusieurs conditions.', 'Combines several conditions.'),
      T(`<p><code>ET</code> est vrai si <strong>toutes</strong> les conditions sont vraies. <code>OU</code> est vrai si <strong>au moins une</strong> l'est. On les glisse dans un <code>SI</code>.</p>`, `<p><code>AND</code> is true if <strong>all</strong> conditions are true. <code>OR</code> is true if <strong>at least one</strong> is. You slip them inside an <code>IF</code>.</p>`),
      { syntax: T('=SI(ET(B2>=1000;C2="Oui");100;0)', '=IF(AND(B2>=1000,C2="Yes"),100,0)'), kw: 'and or et ou plusieurs criteres', lessons: ['f5'] }),
    E('sumif', 'fn', T('SOMME.SI', 'SUMIF'), T('Additionne seulement ce qui correspond à un critère.', 'Adds up only what matches a criterion.'),
      T(`<p>Trois ingrédients : <strong>où chercher</strong>, <strong>quoi chercher</strong>, <strong>quoi additionner</strong>. Le critère peut être une cellule.</p>`, `<p>Three ingredients: <strong>where to look</strong>, <strong>what to look for</strong>, <strong>what to add up</strong>. The criterion can be a cell.</p>`),
      { syntax: T('=SOMME.SI(A2:A6;D2;B2:B6)', '=SUMIF(A2:A6,D2,B2:B6)'), tip: T('Plusieurs critères : <code>SOMME.SI.ENS</code>.', 'Several criteria: <code>SUMIFS</code>.'), kw: 'somme conditionnelle somme si sumif total par categorie', lessons: ['f7', 'p2'] }),
    E('countif', 'fn', T('NB.SI', 'COUNTIF'), T('Compte les cellules qui respectent un critère.', 'Counts the cells that meet a criterion.'),
      T(`<p>Compte combien de cellules d'une plage valent le critère. On peut aussi compter avec une condition : <code>"&gt;100"</code>.</p>`, `<p>Counts how many cells in a range match the criterion. You can also count with a condition: <code>"&gt;100"</code>.</p>`),
      { syntax: T('=NB.SI(B2:B7;D2)', '=COUNTIF(B2:B7,D2)'), kw: 'compter si countif nombre de livres statut', lessons: ['f8', 'p2'] }),
    E('sumifs', 'fn', T('SOMME.SI.ENS et NB.SI.ENS', 'SUMIFS and COUNTIFS'), T('Comme SOMME.SI / NB.SI, avec plusieurs critères.', 'Like SUMIF / COUNTIF, with several criteria.'),
      T(`<p>Chaque critère s'ajoute en paire <em>plage ; critère</em>. Tous doivent être vrais en même temps.</p>`, `<p>Each criterion is added as a <em>range, criterion</em> pair. All must be true at once.</p>`),
      { syntax: T('=SOMME.SI.ENS(C2:C20;A2:A20;"Bougie";B2:B20;"Nord")', '=SUMIFS(C2:C20,A2:A20,"Candle",B2:B20,"North")'), kw: 'plusieurs criteres sumifs countifs', lessons: [] }),
    E('vlookup', 'fn', T('RECHERCHEV', 'VLOOKUP'), T('Retrouve une information dans un tableau.', 'Finds a piece of information in a table.'),
      T(`<p>Cherche une valeur dans la <strong>première colonne</strong> du tableau, puis renvoie la valeur d'une autre colonne de la même ligne. Termine par <code>FAUX</code> pour une correspondance exacte.</p>`, `<p>Looks for a value in the <strong>first column</strong> of the table, then returns a value from another column of the same row. Finish with <code>FALSE</code> for an exact match.</p>`),
      { syntax: T('=RECHERCHEV(E2;A2:C5;3;FAUX)', '=VLOOKUP(E2,A2:C5,3,FALSE)'), tip: T('Sans <code>FAUX</code>, Excel peut se tromper sans afficher d\'erreur.', 'Without <code>FALSE</code>, Excel can be wrong without showing an error.'), kw: 'vlookup rechercher chercher trouver prix par code lookup', lessons: ['f10'] }),
    E('index-match', 'fn', T('INDEX + EQUIV', 'INDEX + MATCH'), T('Une recherche plus flexible que RECHERCHEV.', 'A lookup more flexible than VLOOKUP.'),
      T(`<p><code>EQUIV</code> donne la <strong>position</strong> d'une valeur dans une plage. <code>INDEX</code> renvoie la valeur située à une position. Ensemble, elles cherchent dans <strong>n'importe quelle colonne</strong>.</p>`, `<p><code>MATCH</code> gives the <strong>position</strong> of a value in a range. <code>INDEX</code> returns the value at a position. Together they search <strong>any column</strong>.</p>`),
      { syntax: T('=INDEX(C2:C5;EQUIV(E2;B2:B5;0))', '=INDEX(C2:C5,MATCH(E2,B2:B5,0))'), kw: 'index match equiv recherche gauche lookup', lessons: ['f11'] }),
    E('xlookup', 'fn', T('RECHERCHEX', 'XLOOKUP'), T('La recherche moderne d\'Excel 365 / 2021.', 'Modern lookup in Excel 365 / 2021.'),
      T(`<p>Remplace RECHERCHEV et INDEX/EQUIV : plus simple, cherche dans n'importe quel sens et gère l'« introuvable » directement. Disponible seulement dans les versions récentes d'Excel.</p>`, `<p>Replaces VLOOKUP and INDEX/MATCH: simpler, searches in any direction and handles "not found" directly. Only available in recent versions of Excel.</p>`),
      { syntax: T('=RECHERCHEX(E2;B2:B5;C2:C5;"Introuvable")', '=XLOOKUP(E2,B2:B5,C2:C5,"Not found")'), kw: 'xlookup recherchex lookup nouveau', lessons: [] }),
    E('iferror', 'fn', T('SIERREUR', 'IFERROR'), T('Remplace une erreur par un message.', 'Replaces an error with a message.'),
      T(`<p>Entoure une formule : si elle donne une erreur, Excel affiche ta valeur de remplacement. Attention : elle masque <strong>toutes</strong> les erreurs, même les vraies fautes.</p>`, `<p>Wraps a formula: if it gives an error, Excel shows your replacement value. Careful: it hides <strong>all</strong> errors, even real mistakes.</p>`),
      { syntax: T('=SIERREUR(RECHERCHEV(E2;A2:C5;3;FAUX);"Introuvable")', '=IFERROR(VLOOKUP(E2,A2:C5,3,FALSE),"Not found")'), kw: 'iferror erreur masquer na', lessons: ['f12'] }),
    E('round', 'fn', T('ARRONDI, ARRONDI.SUP', 'ROUND, ROUNDUP'), T('Arrondit un nombre.', 'Rounds a number.'),
      T(`<p><code>ARRONDI</code> arrondit au plus proche, <code>ARRONDI.SUP</code> toujours vers le haut, <code>ARRONDI.INF</code> vers le bas. Le dernier chiffre est le nombre de décimales (0 = entier).</p>`, `<p><code>ROUND</code> rounds to the nearest, <code>ROUNDUP</code> always up, <code>ROUNDDOWN</code> down. The last number is the decimal places (0 = whole number).</p>`),
      { syntax: T('=ARRONDI.SUP(213,3;0)  → 214', '=ROUNDUP(213.3,0)  → 214'), kw: 'arrondir round roundup arrondi sup decimales', lessons: ['m3'] }),

    /* ------------------------------------------------------------ basics */
    E('formula-basics', 'basics', T('Écrire une formule', 'Writing a formula'), T('Toute formule commence par =.', 'Every formula starts with =.'),
      T(`<p>Une formule <strong>commence toujours par <code>=</code></strong>. Ensuite tu écris le calcul avec des <strong>adresses de cellules</strong> (<code>B2</code>) plutôt que des chiffres tapés : si une valeur change, le résultat se met à jour. Opérateurs : <code>+</code> <code>-</code> <code>*</code> <code>/</code> et <code>^</code> (puissance).</p>
         <p>Ordre des calculs : parenthèses, puis puissance, puis × et ÷, puis + et −. Utilise des parenthèses pour être sûr·e.</p>`,
        `<p>A formula <strong>always starts with <code>=</code></strong>. Then you write the calculation with <strong>cell addresses</strong> (<code>B2</code>) instead of typed numbers: if a value changes, the result updates. Operators: <code>+</code> <code>-</code> <code>*</code> <code>/</code> and <code>^</code> (power).</p>
         <p>Order of operations: parentheses, then power, then × and ÷, then + and −. Use parentheses to be safe.</p>`),
      { syntax: T('=B2*C2', '=B2*C2'), kw: 'formule commencer egal operateurs multiplication addition calcul ordre priorite', lessons: ['f1'] }),
    E('cell-reference', 'basics', T('Références de cellules', 'Cell references'), T('B2 = colonne B, ligne 2.', 'B2 = column B, row 2.'),
      T(`<p>Chaque cellule a une adresse : la <strong>lettre</strong> de sa colonne puis le <strong>numéro</strong> de sa ligne. Quand tu recopies une formule vers le bas, la référence <strong>glisse</strong> : <code>B2</code> devient <code>B3</code>, <code>B4</code>… C'est la « référence relative ».</p>`, `<p>Each cell has an address: the <strong>letter</strong> of its column then the <strong>number</strong> of its row. When you copy a formula down, the reference <strong>slides</strong>: <code>B2</code> becomes <code>B3</code>, <code>B4</code>… That's a "relative reference".</p>`),
      { kw: 'adresse cellule reference relative colonne ligne recopier', lessons: ['f1', 'f6'] }),
    E('absolute-ref', 'basics', T('Référence absolue ($)', 'Absolute reference ($)'), T('Verrouille une cellule quand on recopie.', 'Locks a cell when copying.'),
      T(`<p>Ajoute des <code>$</code> pour que la référence ne bouge plus : <code>$E$1</code> reste <code>$E$1</code> même recopiée. Idéal pour un taux de taxe ou un paramètre unique.</p><p><code>$E$1</code> bloque colonne et ligne, <code>E$1</code> bloque la ligne, <code>$E1</code> bloque la colonne.</p>`, `<p>Add <code>$</code> signs so the reference no longer moves: <code>$E$1</code> stays <code>$E$1</code> even when copied. Ideal for a tax rate or a single parameter.</p><p><code>$E$1</code> locks column and row, <code>E$1</code> locks the row, <code>$E1</code> locks the column.</p>`),
      { syntax: T('=B2*(1+$E$1)', '=B2*(1+$E$1)'), tip: T('F4 ajoute les $ pendant que tu écris.', 'F4 adds the $ while you type.'), kw: 'dollar verrouiller figer reference absolue f4 taux tva taxe', lessons: ['f6'] }),
    E('range', 'basics', T('Plage de cellules', 'Cell range'), T('B2:B5 = toutes les cellules de B2 à B5.', 'B2:B5 = every cell from B2 to B5.'),
      T(`<p>Une plage s'écrit <code>première:dernière</code> avec deux-points. Elle peut être une colonne (<code>B2:B5</code>), une ligne (<code>B2:E2</code>) ou un rectangle (<code>A1:C10</code>).</p>`, `<p>A range is written <code>first:last</code> with a colon. It can be a column (<code>B2:B5</code>), a row (<code>B2:E2</code>) or a rectangle (<code>A1:C10</code>).</p>`),
      { kw: 'plage range deux points intervalle selection', lessons: ['f2'] }),
    E('fill-handle', 'basics', T('Poignée de recopie', 'Fill handle'), T('Copier une formule vers le bas en un geste.', 'Copy a formula down in one move.'),
      T(`<p>Le petit carré en bas à droite de la cellule sélectionnée. <strong>Double-clique</strong> dessus pour recopier jusqu'en bas des données, ou <strong>glisse-le</strong>. Raccourci : <kbd>Ctrl</kbd> + <kbd>D</kbd> recopie la cellule du dessus.</p>`, `<p>The small square at the bottom-right of the selected cell. <strong>Double-click</strong> it to copy down to the end of the data, or <strong>drag</strong> it. Shortcut: <kbd>Ctrl</kbd> + <kbd>D</kbd> copies the cell above.</p>`),
      { kw: 'recopier copier vers le bas glisser poignee fill', lessons: ['f1', 'p2'] }),
    E('text-vs-number', 'basics', T('Texte ou nombre ?', 'Text or number?'), T('Un nombre aligné à gauche est souvent du texte.', 'A left-aligned number is often text.'),
      T(`<p>Par défaut, les <strong>nombres</strong> s'alignent à droite et le <strong>texte</strong> à gauche. Si un chiffre est collé à gauche, c'est du texte : il ne s'additionne pas. Cause fréquente : une unité tapée dans la cellule (« 12 pièces ») ou une apostrophe devant.</p>`, `<p>By default, <strong>numbers</strong> align right and <strong>text</strong> left. If a figure hugs the left, it's text: it won't add up. Common cause: a unit typed in the cell ("12 pieces") or a leading apostrophe.</p>`),
      { kw: 'nombre texte alignement ne s additionne pas', lessons: ['t1'] }),
    E('dates', 'basics', T('Les dates sont des nombres', 'Dates are numbers'), T('Excel compte les jours depuis 1900.', 'Excel counts days since 1900.'),
      T(`<p>Une date est un nombre (le nombre de jours écoulés). C'est pour ça qu'on peut <strong>ajouter 30 jours</strong> à une date avec un simple <code>+30</code>. Si tu vois <code>45663</code> au lieu d'une date, applique le format Date : <kbd>Ctrl</kbd> + <kbd>1</kbd> → Date.</p>`, `<p>A date is a number (the days elapsed). That's why you can <strong>add 30 days</strong> to a date with a simple <code>+30</code>. If you see <code>45663</code> instead of a date, apply the Date format: <kbd>Ctrl</kbd> + <kbd>1</kbd> → Date.</p>`),
      { syntax: T('=C8+D8', '=C8+D8'), kw: 'date nombre serie format jours ajouter echeance', lessons: ['t2', 'p2'] }),
    E('number-format', 'basics', T('Formats de nombre ($, %, date)', 'Number formats ($, %, date)'), T('Change l\'affichage sans changer la valeur.', 'Changes the display without changing the value.'),
      T(`<p><kbd>Ctrl</kbd> + <kbd>1</kbd> ouvre <em>Format de cellule</em>. <strong>Monétaire</strong> ajoute le signe $. <strong>Pourcentage</strong> multiplie par 100 à l'affichage (0,2 s'affiche 20 %). <strong>Date</strong> transforme un nombre en date. La valeur reste intacte.</p>`, `<p><kbd>Ctrl</kbd> + <kbd>1</kbd> opens <em>Format Cells</em>. <strong>Currency</strong> adds the $ sign. <strong>Percentage</strong> multiplies by 100 for display (0.2 shows as 20%). <strong>Date</strong> turns a number into a date. The value stays intact.</p>`),
      { kw: 'format cellule monetaire dollar pourcentage date devise ctrl 1 afficher', lessons: ['p1', 't2', 'p2'] }),
    E('percent', 'basics', T('Les pourcentages', 'Percentages'), T('20 % est stocké comme 0,2.', '20% is stored as 0.2.'),
      T(`<p>Un pourcentage est un nombre : <code>20 %</code> vaut <code>0,2</code>. Pour ajouter une taxe de 5 % : <code>=prix*(1+0,05)</code>. Applique le format Pourcentage pour l'affichage.</p>`, `<p>A percentage is a number: <code>20%</code> equals <code>0.2</code>. To add 5% tax: <code>=price*(1+0.05)</code>. Apply the Percentage format for display.</p>`),
      { kw: 'pourcentage taux pct 0,2 taxe', lessons: ['f6', 'm2'] }),
    E('table-structure', 'basics', T('Bien structurer ses données', 'Structuring your data well'), T('Une ligne = un élément, une colonne = une information.', 'One row = one item, one column = one piece of information.'),
      T(`<p>Une liste propre : en-têtes sur la première ligne, <strong>une ligne par élément</strong> (une vente, un client), <strong>une colonne par information</strong>, aucune ligne ni colonne vide au milieu, aucune cellule fusionnée, un seul type de donnée par colonne.</p>`, `<p>A clean list: headers on the first row, <strong>one row per item</strong> (a sale, a client), <strong>one column per piece of information</strong>, no empty row or column in the middle, no merged cells, one type of data per column.</p>`),
      { kw: 'structure liste donnees propres en tete colonne ligne organiser', lessons: ['t1'] }),
    E('merged-cells', 'basics', T('Cellules fusionnées', 'Merged cells'), T('Jolies pour un titre, dangereuses dans les données.', 'Fine for a title, risky in data.'),
      T(`<p>Fusionner des cellules <strong>bloque le tri, les filtres et les tableaux croisés</strong>. Garde-les pour un titre décoratif, jamais dans la zone de données. Alternative : <em>Centrer sur plusieurs colonnes</em>.</p>`, `<p>Merging cells <strong>blocks sorting, filters and pivot tables</strong>. Keep them for a decorative title, never in the data area. Alternative: <em>Center Across Selection</em>.</p>`),
      { kw: 'fusionner fusion merge', lessons: ['t1'] }),
    E('excel-table', 'basics', T('Tableau Excel (Ctrl + T)', 'Excel table (Ctrl + T)'), T('Filtres, lignes alternées, grandit tout seul.', 'Filters, banded rows, grows by itself.'),
      T(`<p>Clique dans ta liste, <kbd>Ctrl</kbd> + <kbd>T</kbd>, coche « Mon tableau comporte des en-têtes ». Excel ajoute des boutons de filtre, une mise en forme et <strong>étend le tableau</strong> quand tu ajoutes une ligne. Donne-lui un nom dans <em>Création de tableau</em>.</p>
         <p>Dans un tableau, les formules peuvent utiliser des noms de colonnes (<code>[@Quantité]</code>).</p>`,
        `<p>Click inside your list, <kbd>Ctrl</kbd> + <kbd>T</kbd>, tick "My table has headers". Excel adds filter buttons, formatting, and <strong>extends the table</strong> when you add a row. Name it under <em>Table Design</em>.</p>
         <p>Inside a table, formulas can use column names (<code>[@Quantity]</code>).</p>`),
      { kw: 'tableau structure ctrl t filtre table lignes alternees', lessons: ['t2'] }),
    E('sort-filter', 'basics', T('Trier et filtrer', 'Sort and filter'), T('Voir les données autrement sans les casser.', 'See your data differently without breaking it.'),
      T(`<p>Les boutons de filtre (flèches dans l'en-tête) permettent de <strong>trier</strong> (A→Z, du plus grand au plus petit) et de <strong>filtrer</strong> (ne voir que « Studio Nomade »). Les lignes masquées existent toujours. Pour retirer le filtre : <em>Données → Effacer</em>.</p>`, `<p>Filter buttons (arrows in the header) let you <strong>sort</strong> (A→Z, largest to smallest) and <strong>filter</strong> (show only "Studio Nomade"). Hidden rows still exist. To remove the filter: <em>Data → Clear</em>.</p>`),
      { kw: 'trier filtrer tri filtre masquer ordre', lessons: ['t2'] }),
    E('freeze-panes', 'basics', T('Figer les volets', 'Freeze panes'), T('Garde l\'en-tête visible en faisant défiler.', 'Keeps the header visible while scrolling.'),
      T(`<p><em>Affichage → Figer les volets → Figer la ligne supérieure</em>. Pour figer plusieurs lignes, sélectionne la première ligne <em>sous</em> la zone à figer, puis <em>Figer les volets</em>.</p>`, `<p><em>View → Freeze Panes → Freeze Top Row</em>. To freeze several rows, select the first row <em>below</em> the area to freeze, then <em>Freeze Panes</em>.</p>`),
      { kw: 'figer volets freeze entete visible defiler', lessons: ['t2', 'p2'] }),
    E('cond-format', 'basics', T('Mise en forme conditionnelle', 'Conditional formatting'), T('Des couleurs qui s\'appliquent toutes seules.', 'Colours that apply by themselves.'),
      T(`<p>Excel colore une cellule selon sa valeur. <em>Accueil → Mise en forme conditionnelle → Nouvelle règle → Utiliser une formule</em>. Exemple : <code>=$I8=$K$8</code> colore en vert les cellules de la colonne I égales au mot de K8. Une règle par couleur.</p>`, `<p>Excel colours a cell depending on its value. <em>Home → Conditional Formatting → New Rule → Use a formula</em>. Example: <code>=$I8=$K$8</code> colours green the cells in column I equal to the word in K8. One rule per colour.</p>`),
      { kw: 'mise en forme conditionnelle couleur automatique regle statut conditional', lessons: ['p2', 't2'] }),
    E('data-validation', 'basics', T('Liste déroulante', 'Dropdown list'), T('Limite la saisie à quelques choix.', 'Limits entry to a few choices.'),
      T(`<p>Sélectionne les cellules → <em>Données → Validation des données</em> → Autoriser : <em>Liste</em> → Source : une plage (<code>=$K$8:$K$10</code>) ou des mots séparés par des virgules. Fini les fautes de frappe dans les statuts.</p>`, `<p>Select the cells → <em>Data → Data Validation</em> → Allow: <em>List</em> → Source: a range (<code>=$K$8:$K$10</code>) or comma-separated words. No more typos in statuses.</p>`),
      { kw: 'liste deroulante validation donnees menu choix dropdown', lessons: ['p2'] }),
    E('pivot', 'basics', T('Tableau croisé dynamique', 'Pivot table'), T('Résume de grandes listes en glissant des champs.', 'Summarises big lists by dragging fields.'),
      T(`<p><em>Insertion → Tableau croisé dynamique</em>. Quatre zones : <strong>Lignes</strong> et <strong>Colonnes</strong> (ce qu'on regroupe), <strong>Valeurs</strong> (ce qu'on calcule : somme, nombre, moyenne), <strong>Filtres</strong>. Le tableau se met à jour quand tu actualises (clic droit → Actualiser).</p>`, `<p><em>Insert → PivotTable</em>. Four areas: <strong>Rows</strong> and <strong>Columns</strong> (what you group by), <strong>Values</strong> (what you calculate: sum, count, average), <strong>Filters</strong>. The table updates when you refresh (right-click → Refresh).</p>`),
      { kw: 'tcd tableau croise dynamique pivot lignes colonnes valeurs resume synthese', lessons: ['v1', 'v2'] }),
    E('slicer', 'basics', T('Segment (slicer)', 'Slicer'), T('Des boutons pour filtrer un tableau croisé.', 'Buttons to filter a pivot table.'),
      T(`<p>Clique dans le tableau croisé → <em>Analyse du tableau croisé dynamique → Insérer un segment</em>, choisis un champ. Tu obtiens des boutons pour filtrer d'un clic.</p>`, `<p>Click inside the pivot table → <em>PivotTable Analyze → Insert Slicer</em>, choose a field. You get buttons to filter in one click.</p>`),
      { kw: 'segment slicer filtre bouton', lessons: ['v2'] }),
    E('chart-basics', 'basics', T('Créer un graphique', 'Creating a chart'), T('Un secteur, des barres ou une courbe.', 'A pie, bars or a line.'),
      T(`<p>Sélectionne les étiquettes et les valeurs, puis <em>Insertion → Graphique recommandé</em>. <strong>Secteurs</strong> pour des parts d'un tout, <strong>barres</strong> pour comparer, <strong>courbe</strong> pour une évolution dans le temps. Moins il y a de couleurs, mieux c'est.</p>`, `<p>Select the labels and values, then <em>Insert → Recommended Charts</em>. <strong>Pie</strong> for parts of a whole, <strong>bars</strong> to compare, <strong>line</strong> for change over time. The fewer colours, the better.</p>`),
      { kw: 'graphique secteur barres courbe chart camembert', lessons: ['p1', 'p2'] }),
    E('download-open', 'basics', T('Télécharger et ouvrir un fichier Excel', 'Downloading and opening an Excel file'), T('Où va le fichier et comment l\'ouvrir.', 'Where the file goes and how to open it.'),
      T(`<p><strong>Windows :</strong> le fichier va dans <em>Téléchargements</em>. Dans Chrome ou Edge, clique sur la flèche ↓ en haut à droite puis sur le fichier. Dans l'Explorateur, ouvre <em>Téléchargements</em> et double-clique. Si Excel s'ouvre en « Mode protégé », clique <em>Activer la modification</em>.</p>
         <p><strong>iPad :</strong> dans Safari, touche l'icône ↓ en haut à droite → <em>Téléchargements</em> → le fichier, puis <em>Partager → Excel</em>. Ou ouvre l'app <em>Fichiers</em> → <em>Téléchargements</em> et touche le fichier.</p>
         <p>Enregistre-le sous un nouveau nom pour garder l'original.</p>`,
        `<p><strong>Windows:</strong> the file goes to <em>Downloads</em>. In Chrome or Edge, click the ↓ arrow at the top right then the file. In File Explorer, open <em>Downloads</em> and double-click. If Excel opens in "Protected View", click <em>Enable Editing</em>.</p>
         <p><strong>iPad:</strong> in Safari, tap the ↓ icon at the top right → <em>Downloads</em> → the file, then <em>Share → Excel</em>. Or open the <em>Files</em> app → <em>Downloads</em> and tap the file.</p>
         <p>Save it under a new name to keep the original.</p>`),
      { kw: 'telecharger ouvrir fichier xlsx trouver telechargements download open introuvable mode protege', lessons: ['p1', 'p2', 't2', 'v2'] }),

    /* ------------------------------------------------------------ shortcuts */
    E('keys-essential', 'keys', T('Raccourcis essentiels (Windows)', 'Essential shortcuts (Windows)'), T('Les dix à connaître.', 'The ten to know.'),
      T(`<p><kbd>Ctrl</kbd>+<kbd>Z</kbd> annuler · <kbd>Ctrl</kbd>+<kbd>Y</kbd> rétablir · <kbd>Ctrl</kbd>+<kbd>C</kbd>/<kbd>V</kbd> copier/coller · <kbd>Ctrl</kbd>+<kbd>1</kbd> format de cellule · <kbd>F2</kbd> modifier la cellule · <kbd>F4</kbd> verrouiller une référence · <kbd>Alt</kbd>+<kbd>=</kbd> somme automatique · <kbd>Ctrl</kbd>+<kbd>T</kbd> tableau · <kbd>Ctrl</kbd>+<kbd>D</kbd> recopier vers le bas · <kbd>Ctrl</kbd>+<kbd>Flèche</kbd> sauter au bout des données.</p>`, `<p><kbd>Ctrl</kbd>+<kbd>Z</kbd> undo · <kbd>Ctrl</kbd>+<kbd>Y</kbd> redo · <kbd>Ctrl</kbd>+<kbd>C</kbd>/<kbd>V</kbd> copy/paste · <kbd>Ctrl</kbd>+<kbd>1</kbd> format cells · <kbd>F2</kbd> edit the cell · <kbd>F4</kbd> lock a reference · <kbd>Alt</kbd>+<kbd>=</kbd> auto-sum · <kbd>Ctrl</kbd>+<kbd>T</kbd> table · <kbd>Ctrl</kbd>+<kbd>D</kbd> fill down · <kbd>Ctrl</kbd>+<kbd>Arrow</kbd> jump to the end of the data.</p>`),
      { kw: 'raccourcis clavier shortcuts touches ctrl', lessons: ['k1'] }),
    E('key-select', 'keys', T('Sélectionner vite', 'Selecting fast'), T('Ctrl + Maj + Flèche.', 'Ctrl + Shift + Arrow.'),
      T(`<p><kbd>Ctrl</kbd>+<kbd>Flèche</kbd> saute au bout des données. Avec <kbd>Maj</kbd>, tu <strong>sélectionnes</strong> tout le trajet. <kbd>Ctrl</kbd>+<kbd>A</kbd> sélectionne toute la liste. <kbd>Ctrl</kbd>+clic ajoute des zones séparées.</p>`, `<p><kbd>Ctrl</kbd>+<kbd>Arrow</kbd> jumps to the end of the data. Adding <kbd>Shift</kbd> <strong>selects</strong> the whole way. <kbd>Ctrl</kbd>+<kbd>A</kbd> selects the whole list. <kbd>Ctrl</kbd>+click adds separate areas.</p>`),
      { kw: 'selectionner selection ctrl shift fleche', lessons: ['k1'] }),
    E('key-f4', 'keys', T('F4 : verrouiller / répéter', 'F4: lock / repeat'), T('Alterne B2, $B$2, B$2, $B2.', 'Cycles B2, $B$2, B$2, $B2.'),
      T(`<p>Pendant que tu écris une référence, <kbd>F4</kbd> ajoute les <code>$</code>. En dehors d'une formule, <kbd>F4</kbd> répète la dernière action.</p>`, `<p>While you type a reference, <kbd>F4</kbd> adds the <code>$</code>. Outside a formula, <kbd>F4</kbd> repeats the last action.</p>`),
      { kw: 'f4 dollar verrouiller', lessons: ['f6', 'k1'] }),
    E('key-autosum', 'keys', T('Alt + = (somme automatique)', 'Alt + = (auto-sum)'), T('Écrit la SOMME pour toi.', 'Writes the SUM for you.'),
      T(`<p>Place-toi sous une colonne de chiffres (ou à droite d'une ligne) et appuie sur <kbd>Alt</kbd>+<kbd>=</kbd> : Excel propose <code>=SOMME(…)</code>. <kbd>Entrée</kbd> pour valider.</p>`, `<p>Stand under a column of numbers (or to the right of a row) and press <kbd>Alt</kbd>+<kbd>=</kbd>: Excel offers <code>=SUM(…)</code>. <kbd>Enter</kbd> to confirm.</p>`),
      { kw: 'alt egal somme automatique autosum', lessons: ['f2', 'k1'] }),
    E('key-format', 'keys', T('Ctrl + 1 (format de cellule)', 'Ctrl + 1 (format cells)'), T('Nombres, dates, alignement, bordures, remplissage.', 'Numbers, dates, alignment, borders, fill.'),
      T(`<p>Ouvre la fenêtre <em>Format de cellule</em> : onglet <em>Nombre</em> (monétaire, pourcentage, date), <em>Alignement</em>, <em>Bordure</em>, <em>Remplissage</em>. À utiliser dès que l'affichage d'une cellule ne te convient pas.</p>`, `<p>Opens the <em>Format Cells</em> window: <em>Number</em> tab (currency, percentage, date), <em>Alignment</em>, <em>Border</em>, <em>Fill</em>. Use it whenever a cell's display doesn't suit you.</p>`),
      { kw: 'ctrl 1 format cellule', lessons: ['k1', 'p1'] }),

    /* ------------------------------------------------------------ errors */
    E('err-div0', 'err', T('#DIV/0!', '#DIV/0!'), T('Division par zéro.', 'Division by zero.'),
      T(`<p>Tu divises par 0 ou par une cellule <strong>vide</strong>. Vérifie le diviseur. Pour masquer proprement : <code>=SIERREUR(A1/B1;0)</code>.</p>`, `<p>You divide by 0 or by an <strong>empty</strong> cell. Check the divisor. To hide it cleanly: <code>=IFERROR(A1/B1,0)</code>.</p>`),
      { kw: 'div 0 zero division erreur', lessons: ['k2'] }),
    E('err-na', 'err', T('#N/A', '#N/A'), T('Valeur introuvable.', 'Value not found.'),
      T(`<p>Une recherche (RECHERCHEV, EQUIV) ne trouve pas la valeur. Causes fréquentes : faute de frappe, <strong>espace en trop</strong>, nombre stocké comme du texte, ou valeur absente de la <strong>première colonne</strong> du tableau.</p>`, `<p>A lookup (VLOOKUP, MATCH) can't find the value. Common causes: typo, <strong>extra space</strong>, number stored as text, or value missing from the table's <strong>first column</strong>.</p>`),
      { kw: 'na introuvable recherchev erreur not available', lessons: ['k2', 'f12'] }),
    E('err-ref', 'err', T('#REF!', '#REF!'), T('La cellule pointée n\'existe plus.', 'The referenced cell no longer exists.'),
      T(`<p>Tu as supprimé une ligne, une colonne ou une feuille utilisée par la formule. Annule avec <kbd>Ctrl</kbd>+<kbd>Z</kbd> ou réécris la formule.</p>`, `<p>You deleted a row, column or sheet that the formula used. Undo with <kbd>Ctrl</kbd>+<kbd>Z</kbd> or rewrite the formula.</p>`),
      { kw: 'ref reference supprimee erreur', lessons: ['k2'] }),
    E('err-name', 'err', T('#NOM? / #NAME?', '#NAME?'), T('Nom de fonction inconnu.', 'Unknown function name.'),
      T(`<p>Excel ne reconnaît pas un mot : fonction mal écrite (<code>SOMM</code>) ou <strong>texte sans guillemets</strong> (<code>Oui</code> au lieu de <code>"Oui"</code>). Relis l'orthographe.</p>`, `<p>Excel doesn't recognise a word: misspelled function (<code>SUMM</code>) or <strong>text without quotes</strong> (<code>Yes</code> instead of <code>"Yes"</code>). Re-read the spelling.</p>`),
      { kw: 'nom name fonction inconnue guillemets erreur', lessons: ['k2'] }),
    E('err-value', 'err', T('#VALEUR! / #VALUE!', '#VALUE!'), T('Un calcul avec du texte.', 'A calculation with text.'),
      T(`<p>La formule essaie de calculer avec du texte (ou un nombre stocké comme du texte). Repère la cellule fautive : un espace, une unité tapée, une apostrophe.</p>`, `<p>The formula tries to calculate with text (or a number stored as text). Find the faulty cell: a space, a typed unit, an apostrophe.</p>`),
      { kw: 'valeur value texte erreur calcul', lessons: [] }),
    E('err-hash', 'err', T('########', '########'), T('Colonne trop étroite : ce n\'est pas une vraie erreur.', 'Column too narrow: not a real error.'),
      T(`<p>Le nombre est trop large pour la colonne. <strong>Double-clique</strong> entre deux lettres de colonnes pour ajuster la largeur. Une date négative produit aussi ########.</p>`, `<p>The number is too wide for the column. <strong>Double-click</strong> between two column letters to auto-fit. A negative date also produces ########.</p>`),
      { kw: 'diese hash largeur colonne etroite', lessons: ['k2'] }),

    /* ------------------------------------------------------------ finance */
    E('gross-margin', 'fin', T('Marge brute et taux de marge brute', 'Gross margin and gross margin rate'), T('(prix − coût) ÷ prix.', '(price − cost) ÷ price.'),
      T(`<p>La <strong>marge brute</strong> est ce qu'il reste d'une vente une fois le coût du produit payé. Le <strong>taux de marge brute</strong> la rapporte au <strong>prix de vente</strong>. Ne le confonds pas avec le taux de marge « sur coût ».</p>`, `<p><strong>Gross margin</strong> is what is left of a sale after the product cost is paid. The <strong>gross margin rate</strong> expresses it against the <strong>selling price</strong>. Don't confuse it with the markup "on cost".</p>`),
      { syntax: T('=(B2-C2)/B2', '=(B2-C2)/B2'), kw: 'marge brute taux de marque rentabilite gross margin', lessons: ['m1', 'p1'] }),
    E('markup', 'fin', T('Taux de marge vs taux de marque', 'Markup vs margin rate'), T('Sur le coût, ou sur le prix de vente.', 'On cost, or on the selling price.'),
      T(`<p>Le <strong>taux de marge</strong> (markup) = marge ÷ <strong>coût</strong>. Le <strong>taux de marque</strong> = marge ÷ <strong>prix de vente</strong>. Même marge en dollars, deux pourcentages : avec 50 % de marge sur coût, tu n'as que 33 % de taux de marque. Prix de vente = coût × (1 + taux de marge).</p>`, `<p><strong>Markup</strong> = margin ÷ <strong>cost</strong>. <strong>Margin rate</strong> = margin ÷ <strong>selling price</strong>. Same margin in dollars, two percentages: with a 50% markup on cost you only get a 33% margin rate. Selling price = cost × (1 + markup).</p>`),
      { kw: 'markup marge marque coefficient prix de vente', lessons: ['p1'] }),
    E('pct-change', 'fin', T('Variation en pourcentage', 'Percentage change'), T('(nouveau − ancien) ÷ ancien.', '(new − old) ÷ old.'),
      T(`<p>Divise l'<strong>écart</strong> par la <strong>valeur de départ</strong>. Un résultat négatif est une baisse. Exemple : de 1 200 $ à 1 380 $, l'écart est 180 $, soit +15 %.</p>`, `<p>Divide the <strong>gap</strong> by the <strong>starting value</strong>. A negative result is a decrease. Example: from $1,200 to $1,380, the gap is $180, i.e. +15%.</p>`),
      { syntax: T('=(B3-B2)/B2', '=(B3-B2)/B2'), kw: 'variation croissance evolution pourcentage hausse baisse growth', lessons: ['m2'] }),
    E('break-even', 'fin', T('Seuil de rentabilité (point mort)', 'Break-even point'), T('Combien vendre pour ne plus perdre d\'argent.', 'How much to sell to stop losing money.'),
      T(`<p>Chaque vente rapporte <em>prix − coût variable</em> (la « marge sur coûts variables »). Il faut en vendre assez pour couvrir les <strong>charges fixes</strong> : <code>unités = charges fixes ÷ (prix − coût variable)</code>, arrondi <strong>au-dessus</strong>.</p>`, `<p>Each sale earns <em>price − variable cost</em> (the "contribution margin"). You need enough to cover <strong>fixed costs</strong>: <code>units = fixed costs ÷ (price − variable cost)</code>, rounded <strong>up</strong>.</p>`),
      { syntax: T('=ARRONDI.SUP(B2/(B3-B4);0)', '=ROUNDUP(B2/(B3-B4),0)'), kw: 'seuil rentabilite point mort break even charges fixes', lessons: ['m3'] }),
    E('cash-vs-profit', 'fin', T('Trésorerie ≠ bénéfice', 'Cash ≠ profit'), T('Une entreprise rentable peut manquer d\'argent.', 'A profitable company can run out of cash.'),
      T(`<p>Le <strong>bénéfice</strong> compte une vente dès qu'elle est faite ; la <strong>trésorerie</strong> compte l'argent quand il arrive. Clients qui paient en retard, stock acheté d'avance ou emprunt à rembourser : le bénéfice est là, mais pas le cash. Solde du mois = solde précédent + encaissements − décaissements.</p>`, `<p><strong>Profit</strong> counts a sale as soon as it's made; <strong>cash</strong> counts money when it arrives. Customers paying late, stock bought in advance or a loan to repay: the profit is there but not the cash. Month balance = previous balance + receipts − payments.</p>`),
      { syntax: T('=D2+B3-C3', '=D2+B3-C3'), kw: 'tresorerie cash flow solde encaissement decaissement flux', lessons: ['q3', 'm4'] }),
    E('income-statement', 'fin', T('Compte de résultat', 'Income statement'), T('Produits − charges = résultat, sur une période.', 'Revenue − expenses = result, over a period.'),
      T(`<p>Il raconte une <strong>période</strong> (mois, année) : ce que l'entreprise a gagné (produits, chiffre d'affaires) moins ce qu'elle a dépensé (charges : loyer, matières, salaires). Le reste est le <strong>résultat</strong> : bénéfice si positif, perte si négatif.</p>`, `<p>It tells the story of a <strong>period</strong> (month, year): what the company earned (revenue, sales) minus what it spent (expenses: rent, materials, wages). What's left is the <strong>result</strong>: profit if positive, loss if negative.</p>`),
      { kw: 'compte de resultat income statement p&l produits charges chiffre d affaires benefice perte', lessons: ['q1'] }),
    E('balance-sheet', 'fin', T('Bilan', 'Balance sheet'), T('Une photo : ce qu\'on possède = ce qu\'on doit.', 'A photo: what we own = what we owe.'),
      T(`<p>Le bilan photographie l'entreprise à une <strong>date précise</strong>. <strong>Actif</strong> (ce qu'elle possède : stock, argent, équipement) = <strong>Passif</strong> (dettes + capitaux propres). Toujours égaux.</p>`, `<p>The balance sheet photographs the company at a <strong>specific date</strong>. <strong>Assets</strong> (what it owns: stock, cash, equipment) = <strong>Liabilities + Equity</strong> (debts + owners' funds). Always equal.</p>`),
      { kw: 'bilan balance sheet actif passif capitaux propres dettes', lessons: ['q2'] }),
    E('depreciation', 'fin', T('Amortissement', 'Depreciation'), T('Étaler le coût d\'un équipement sur plusieurs années.', 'Spreading an equipment cost over several years.'),
      T(`<p>Quand tu achètes un équipement, l'argent sort <strong>une fois</strong>. L'amortissement répartit ce coût en charge sur plusieurs années dans le compte de résultat : c'est une charge <strong>sans sortie d'argent</strong>.</p>`, `<p>When you buy equipment, the cash goes out <strong>once</strong>. Depreciation spreads that cost as an expense over several years in the income statement: it's an expense <strong>with no cash outflow</strong>.</p>`),
      { kw: 'amortissement depreciation equipement charge', lessons: ['q3'] }),
    E('compound-interest', 'fin', T('Intérêts composés', 'Compound interest'), T('Les intérêts génèrent des intérêts.', 'Interest earns interest.'),
      T(`<p>Valeur finale = capital × (1 + taux) ^ années. Le signe <code>^</code> veut dire « puissance ». 1 000 $ à 5 % sur 3 ans donnent 1 157,63 $, pas 1 150 $.</p>`, `<p>Final value = capital × (1 + rate) ^ years. The <code>^</code> sign means "power". $1,000 at 5% over 3 years gives $1,157.63, not $1,150.</p>`),
      { syntax: T('=B2*(1+B3)^B4', '=B2*(1+B3)^B4'), kw: 'interets composes valeur future placement capital compound', lessons: ['m5'] }),
    E('sales-tax-ca', 'fin', T('Taxes de vente au Canada', 'Sales taxes in Canada'), T('TPS, TVQ, TVH : selon la province.', 'GST, QST, HST: depending on the province.'),
      T(`<p>La <strong>TPS</strong> fédérale est de 5 %. Au Québec s'ajoute la <strong>TVQ</strong> de 9,975 %. Dans certaines provinces, une <strong>TVH</strong> unique remplace les deux (13 % en Ontario). Dans les leçons, on utilise les taux du Québec : TPS 5 % + TVQ 9,975 % = 14,975 % (la TVQ ne s'applique pas sur la TPS). Pour une autre province, remplace-les par tes taux réels.</p>
         <p>Prix avec taxes = prix × (1 + taux).</p>`,
        `<p>Federal <strong>GST</strong> is 5%. In Quebec, <strong>QST</strong> of 9.975% is added. In some provinces a single <strong>HST</strong> replaces both (13% in Ontario). In the lessons we use Quebec's rates: GST 5% + QST 9.975% = 14.975% (QST is not charged on top of GST). For another province, swap in your real rates.</p>
         <p>Price with tax = price × (1 + rate).</p>`),
      { kw: 'tps tvq tvh gst qst hst taxe tva vente canada quebec ontario', lessons: ['f6', 'p1', 'p2'] }),
    E('budget-basics', 'fin', T('Faire un budget mensuel', 'Building a monthly budget'), T('Prévu, dépensé, reste.', 'Planned, spent, left.'),
      T(`<p>Un budget compare trois choses par catégorie : le <strong>prévu</strong>, le <strong>dépensé</strong> et le <strong>reste</strong> (prévu − dépensé). Un reste négatif veut dire que tu as dépassé.</p>
         <p>Ajoute la part du revenu de chaque catégorie (<code>=C6/$B$3</code>, avec le revenu verrouillé) et une ligne de total.</p>`,
        `<p>A budget compares three things per category: what was <strong>planned</strong>, what was <strong>spent</strong> and what is <strong>left</strong> (planned − spent). A negative amount means you went over.</p>
         <p>Add each category's share of income (<code>=C6/$B$3</code>, with the income locked) and a total row.</p>`),
      { syntax: T('=C6/$B$3', '=C6/$B$3'), kw: 'budget mensuel prevu depense reste revenu depasse categorie epargne', lessons: ['m6'] }),
    E('savings-rate', 'fin', T("Le taux d'épargne",'The savings rate'), T('La part du revenu mise de côté.', 'The share of income set aside.'),
      T(`<p>Taux d'épargne = montant épargné ÷ revenu. Avec 400 $ épargnés sur 3 400 $ de revenu, on obtient 11,8 %. Une règle courante (à adapter à ta situation) : 50 % besoins, 30 % envies, 20 % épargne.</p>`,
        `<p>Savings rate = amount saved ÷ income. With $400 saved out of $3,400 income, you get 11.8%. A common rule of thumb (to adapt to your situation): 50% needs, 30% wants, 20% savings.</p>`),
      { syntax: T('=C11/B3', '=C11/B3'), kw: 'taux epargne economie mettre de cote savings rate 50 30 20', lessons: ['m6'] }),

    /* ------------------------------------------------------------ design */
    E('palette-rules', 'design', T('Choisir une palette lisible', 'Choosing a readable palette'), T('2 ou 3 couleurs, avec des variantes claires.', '2 or 3 colours, with light variants.'),
      T(`<p>Peu de couleurs, bien réparties. Une couleur principale pour l'en-tête, une couleur claire pour les zones de saisie, une autre pour les résultats. Les pastels (rose F9B9D0, bleu A8D3F5, pêche FBC9A0, vert BDE5A6, lilas D3B6F3) marchent bien, avec du texte foncé.</p>`, `<p>Few colours, well distributed. One main colour for the header, a light colour for input areas, another for results. Pastels (pink F9B9D0, blue A8D3F5, peach FBC9A0, green BDE5A6, lilac D3B6F3) work well, with dark text.</p>`),
      { kw: 'palette couleurs pastel hex remplissage palette design', lessons: ['d1', 'p1'] }),
    E('inputs-vs-results', 'design', T('Cases à remplir vs cases calculées', 'Input cells vs calculated cells'), T('Un code couleur que tout le monde comprend.', 'A colour code everyone understands.'),
      T(`<p>Donne toujours la même couleur claire aux cases où l'on tape, et une autre aux cases qui se calculent. L'utilisateur sait en 5 secondes où il peut écrire sans casser une formule.</p>`, `<p>Always give the same light colour to cells where people type, and another to cells that calculate. The user knows in 5 seconds where they can write without breaking a formula.</p>`),
      { kw: 'saisie resultat couleur code input', lessons: ['d1', 'p1'] }),
    E('number-alignment', 'design', T('Alignement des nombres', 'Number alignment'), T('À droite, même format partout.', 'Right-aligned, same format throughout.'),
      T(`<p>Les nombres s'alignent à droite avec le même nombre de décimales : unités sous unités, dizaines sous dizaines. Les textes à gauche. Les en-têtes de colonnes de nombres se justifient à droite aussi.</p>`, `<p>Numbers right-align with the same number of decimals: units under units, tens under tens. Text left-aligns. Headers of number columns right-align too.</p>`),
      { kw: 'alignement droite gauche decimales', lessons: ['d1'] }),
    E('contrast', 'design', T('Contraste texte / fond', 'Text / background contrast'), T('Texte foncé sur fond clair.', 'Dark text on a light background.'),
      T(`<p>Un fond pastel demande un texte foncé. Du blanc sur du pastel se lit très mal, surtout sur un écran d'iPad en pleine lumière. Test simple : plisse les yeux, le texte doit rester lisible.</p>`, `<p>A pastel background needs dark text. White on pastel is hard to read, especially on an iPad screen in bright light. Simple test: squint, the text should stay readable.</p>`),
      { kw: 'contraste lisibilite texte fond couleur', lessons: ['d1'] }),
  ];

  /* ---------------------------------------------------------------- which entries help which lesson / question */
  window.NOTES_FOR = {
    f1: ['formula-basics', 'cell-reference', 'fill-handle'],
    f2: ['sum', 'range', 'key-autosum'], f3: ['average', 'range'], f4: ['minmax', 'formula-basics'],
    f5: ['if', 'and-or'], f6: ['absolute-ref', 'key-f4', 'percent', 'sales-tax-ca'], f7: ['sumif', 'sumifs'], f8: ['countif', 'sumifs'],
    f9: ['nested-if', 'if'], f10: ['vlookup', 'err-na'], f11: ['index-match', 'vlookup', 'xlookup'], f12: ['iferror', 'err-na'],
    t1: ['table-structure', 'merged-cells', 'text-vs-number', 'dates'], t2: ['download-open', 'number-format', 'dates', 'excel-table', 'freeze-panes', 'sort-filter', 'fill-handle'],
    v1: ['pivot', 'table-structure', 'slicer'], v2: ['download-open', 'pivot', 'slicer'],
    k1: ['keys-essential', 'key-select', 'key-f4', 'key-format', 'key-autosum'], k2: ['err-div0', 'err-na', 'err-ref', 'err-name', 'err-hash', 'err-value'],
    q1: ['income-statement', 'gross-margin'], q2: ['balance-sheet'], q3: ['cash-vs-profit', 'depreciation'],
    d1: ['palette-rules', 'inputs-vs-results', 'number-alignment', 'contrast'],
    p1: ['download-open', 'number-format', 'markup', 'sales-tax-ca', 'absolute-ref', 'palette-rules', 'inputs-vs-results'],
    p2: ['download-open', 'countif', 'sumif', 'dates', 'data-validation', 'cond-format', 'number-format', 'freeze-panes'],
    m1: ['gross-margin', 'markup'], m2: ['pct-change', 'percent'], m3: ['break-even', 'round'], m4: ['cash-vs-profit'], m5: ['compound-interest', 'percent'],
    m6: ['budget-basics', 'savings-rate', 'absolute-ref', 'countif', 'number-format', 'cond-format', 'inputs-vs-results', 'freeze-panes'],
  };
  // Question-specific help (key = "lessonId:questionIndex"); falls back to the lesson's list.
  window.NOTES_FOR_Q = {
    't1:0': ['table-structure'], 't1:1': ['merged-cells'], 't1:2': ['text-vs-number'], 't1:3': ['dates'],
    'v1:0': ['pivot'], 'v1:1': ['pivot'], 'v1:2': ['pivot'], 'v1:3': ['pivot'],
    'k1:0': ['keys-essential'], 'k1:1': ['key-select'], 'k1:2': ['key-f4', 'absolute-ref'], 'k1:3': ['key-format', 'number-format'], 'k1:4': ['key-autosum'],
    'k2:0': ['err-div0'], 'k2:1': ['err-na'], 'k2:2': ['err-ref'], 'k2:3': ['err-hash'], 'k2:4': ['err-name'],
    'q1:0': ['income-statement'], 'q1:1': ['income-statement'], 'q1:2': ['income-statement'],
    'q2:0': ['balance-sheet'], 'q2:1': ['balance-sheet'], 'q2:2': ['balance-sheet'],
    'q3:0': ['cash-vs-profit'], 'q3:1': ['cash-vs-profit'], 'q3:2': ['depreciation'],
    'd1:0': ['palette-rules'], 'd1:1': ['inputs-vs-results'], 'd1:2': ['number-alignment'], 'd1:3': ['contrast'],
  };
})();
